const mongoose = require('mongoose');
const User = require('../userSchema/userSchema')
const LocationSchema = require('../locationSchema/locationSchema')
const imageObjSchema = require('../imageObjSchema/imageObjSchema')
const { v4: uuidv4 } = require('uuid');
const CarSchema = mongoose.model('CarSchema',{
    bodyType:{
        type:String,
        required:false
    },
    brand:{
        type:String,
        required:false
    },
    condition:{
        type:String,
        required:false
    },
    description:{
        type:String,
        required:false
    },
    fuelType:{
        type:String,
        required:false
    },
    kilometres:{
        type:String,
        required:false
    },
    model:{
        type:String,
        required:false
    },
    price:{
        type:String,
        required:false
    },
    title:{
        type:String,
        required:false
    },
    transmission:{
        type:String,
        required:false
    },
    trim:{
        type:String,
        required:false
    },
    year:{
        type:String,
        required:false
    },
    userDetail:{
        type:String,
        required:false
    },
    location:{
        type:LocationSchema,
        required:false
    },
    carImages:[imageObjSchema],
    mainImage:{
        type:String,
        required:false
    },
    date:{
        type:Date,
        default:Date.now
    },
    postId:{
        type:String,
        required:false,
    },
    sellerType:{
        type:String,
        required:false
    },
    exteriorColor:{
        type:String,
        required:false
    },
    cylinders:{
        type:Number,
        required:false
    },
    engineSize:{
        type:Number,
        required:false
    },
    power:{
        type:Number,
        required:false
    },
    seatCount:{
        type:Number,
        required:false
    },
    doors:{
        type:Number,
        required:false
    },
    extras:{
        type:String,
        required:false
    },
    driveTrain:{
        type:String,
        required:false
    },
    confirmedSaleUser:{
        type:mongoose.Schema.Types.Mixed,
        required:false
    },
    visiters:[],
    offeredPrices:[]
})

module.exports = CarSchema
